networks:
  pcc_docker_network:
    external: true

services:
  web:
    build:
      context: .
      dockerfile: ./docker/image/web/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/project/pcc:cached
    ports:
      - "13000:3000"
    depends_on:
      - mysql
      - mysql-test
    networks:
      - pcc_docker_network

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    networks:
      - pcc_docker_network
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pcc_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: secret

  mysql-test:
    image: mysql:5.7
    platform: linux/x86_64
    networks:
      - pcc_docker_network
    volumes:
      - ./docker/data/mysql-test:/var/lib/mysql
    ports:
      - "13307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pcc_test
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
